import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import ThemeProvider from './ui/theme-provider';
import { Suspense } from "react";
//import Carousel from './ui/carousel'

import Loading from './loading';
import NotFound from "./not-found";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >{/* Layout UI */}
      <nav>
          {/* Prefetched when the link is hovered or enters the viewport */}
          <Link href="/blog">Blog</Link>
          {/* No prefetching */}
          <Link href="/contact">Contact</Link>
        </nav>
        {/* Place children where you want to render a page or nested layout */}
        <main>
          <Suspense fallback={ < Loading />}>
          
          </Suspense>
          <ThemeProvider>{children}</ThemeProvider>
          <div>
            {/*  Works, since Carousel is a Client Component */}
            /
            {/*<Carousel />*/}
          </div>
          </main>
      </body>
    </html>
  );
}
